org: planetavegetta777

service: api-rotacion-secretos

provider:
  name: aws
  runtime: python3.10
  timeout: 30
  memorySize: 1024

  iam:
    role: arn:aws:iam::174510827120:role/LabRole

  environment:
    DB_HOST_PARAMETER: /rds_mysql_alumnos/punto_enlace

functions:

  rotarPasswords:
    handler: RotarPasswords.lambda_handler

    package:
      include:
        - ./**

    events:
      - schedule:
          rate: rate(10 minutes)
          enabled: true